spring.application.name=ninjas
# URL de conexão com o banco PostgresSQL (endereço + porta + nome do banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas
# Usuário do banco de dados
spring.datasource.username=postgres
# Senha do banco de dados 
spring.datasource.password=@GArcia06032008 
# Driver responsável por fazer a conexão com o PostgresSQL (subtituir por postdba na escola)
spring.datasource.driver-class-name=org.postgresql.Driver
# Define como o Hibernate vai gerenciar as tabelas (update = criar/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto=update
# Mostra no console as consultas SQL executados
spring.jpa.show-sql=true
# Formata o SQL exibindo no console para facilitar leitura
spring.jpa.properties.hibernate.format_sql=true
# Define o tipo de banco utilizado (dialeto do PostgresSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect

